# Generated by Django 2.2.16 on 2020-10-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='currency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='stripe_price_id',
            field=models.CharField(max_length=100),
        ),
    ]
