# Generated by Django 2.2.16 on 2020-10-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201025_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='currency',
        ),
    ]
